language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
before_install:
  - eval "${MATRIX_EVAL}"
before_script:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install libboost1.65-dev -y
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ip_filter03-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usaleksvik:$BINTRAY_API_KEY "https://api.bintray.com/content/saleksvik/cpp_advanced/ip_filter03/$TRAVIS_BUILD_NUMBER/ip_filter03-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
